### ISSUE TITLE
Request for new release for "Control package action via attributes"

### ISSUE THREAD

**Issue by justincmoy** [stevendanna/logrotate#114]
I was wondering if you could release a new version of this cookbook for the below fix:
https://github.com/stevendanna/logrotate/commit/8626eeef82a8dbc80ed6a0894923505958289744

Specifically, I'm running into an issue with yum_package where the version attribute needs the action attribute to be set to :install and not :upgrade: https://docs.chef.io/resource_yum.html
> Install a package and/or ensure that a package is the latest version. This action will ignore the version attribute.

**Comment by stevendanna** [comment]
2.2.0 has been released to supermarket. Thanks for reaching out.
