### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by joelnn** [stevendanna/logrotate#65]
It would be nice to get https://github.com/stevendanna/logrotate/commit/1fcb3ff5366153b3aa7365124628347d83e9364b released, as logrotate::global isn't usable for me without it on Ubuntu 14.04.

By the way, the cookbook has been great, thanks for sharing it!

**Comment by stevendanna** [comment]
@joelnn I'll get a release out this week, thanks for the reminder, I really need to get this out more regularly.  Thanks for the kind words about the cookbook, I am just the current maintainer, many people have contributed to it. :)

**Comment by stevendanna** [comment]
Released 1.8
