### ISSUE TITLE
Setting sharedscripts will be ignored

### ISSUE THREAD

**Issue by thielena** [stevendanna/logrotate#69]
Hi, by setting `sharedscripts` to `true` on `logrotate_app` definition won't work. The setting is just missing in the logrotate file.

Best Regards,
Andreas

**Comment by stevendanna** [comment]
@thielena Thank you for reporting this.  As a workaround, I believe you should still be able to specify sharedscripts as part of the "options" attribute.  I'll get a fix for this out this week.

**Comment by stevendanna** [comment]
v1.9.1 has been released with a fix for this.  Thanks!
