### ISSUE TITLE
Support specify the time of day logrotate is executed?

### ISSUE THREAD

**Issue by wjimenez5271** [stevendanna/logrotate#70]
Curious if you think this would be acceptable to support here. I think that would require you to use a mechanism other than `/etc/cron.daily/`, since that doesn't guarantee time of day run by design, so I understand if it would be stretching the scope of the cookbook.

**Comment by jtimberman** [comment]
I think that should be managed outside this cookbook as it will vary wildly by site. I imagine most sites are probably okay with the default cron job.

**Comment by wjimenez5271** [comment]
OK, I'll take your word for it. Thanks for the feedback.
