### ISSUE TITLE
Version outdated on supermarket

### ISSUE THREAD

**Issue by spuder** [stevendanna/logrotate#72]
The github repo has version 1.9.1, whereas the supermarket only has 1.8.1. Also the readme.md is messed up on supermarket. 

Any plans to update it?

**Comment by stevendanna** [comment]
@spuder I'm seeing 1.9.1 on supermarket.  Mind attaching a screenshot of what you are seeing?

**Comment by spuder** [comment]
Strange, maybe I had the wrong one. Looks fine now.
