### ISSUE TITLE
Anything chef-brigade can do to help?

### ISSUE THREAD

**Issue by josephholsten** [stevendanna/logrotate#74]
Is there anything @chef-brigade can do to help out? We're probably going to start using this in our infra, so we want to keep it awesome.

If you need any administrative help, want a slack channel, website, testing infra &c, just let us know. It doesn't need to have the brigade name anywhere on it.

**Comment by stevendanna** [comment]
Hi @josephholsten!  I don't think there is a ton I need at the moment.  I had planned a 2.0 rewrite, but the sense I got from users is that they would prefer minimal change around the logrotate cookbook, so I've so far tried to keep this rather user-request driven.

Is there a general slack channel for cookbook development that we could maybe direct people too for this one?  Having a whole slack channel just for this cookbook seemsa  bit much as it is pretty simple.

**Comment by josephholsten** [comment]
yeah, there's usually some folks hanging out in https://chef-brigade.slack.com/messages/general/

We've got a little badglet to register for the slack:
```
[![Slack](http://brigade-slackin.herokuapp.com/badge.svg)](https://brigade-slackin.herokuapp.com/)
```

**Comment by stevendanna** [comment]
Thanks @josephholsten I've created an account and look forward to chatting with you all.  For now I'm gonna close this issue since it doesn't represent work that I need to do on the cookbook.  Thanks for reaching out!
