### ISSUE TITLE
Kitchen converge fails if logrotate is a dependency of another cookbook

### ISSUE THREAD

**Issue by vinyar** [stevendanna/logrotate#79]
Bug: Having logrotate > v1.8.0 will cause a 'cant find a folder' error on converge due to a simlink.

Short-term fix is to revert to v1.8.0

I'll hack up a long(er)-term fix that removes a `cookbooks -> test/fixtures/cookbooks` simlink.

**Comment by stevendanna** [comment]
I've removed the symlink.
