### ISSUE TITLE
matcher does not verify path

### ISSUE THREAD

**Issue by dwmarshall** [stevendanna/logrotate#81]
I don't know how to fix it yet, so I can only offer a report at present.

```ruby
    expect(chef_run).to enable_logrotate_app('foo').with(
      cookbook: 'logrotate',
      path: '/install/install-dir/logs/catalina.out',
      rotate: 5,
      su: 'rspec_user rspec_group'
  )
```

doesn't check that I've added the recipe with a correct `path` parameter.

**Comment by gawbul** [comment]
I'm not sure if this is related to an issue I am having. The path is being written for logrotate with `"`'s around it, and this is causing logrotate to fail parsing the path. Not sure if this is fixed in newer versions of logrotate?

**Comment by gawbul** [comment]
Ah, I was passing the path in as one long string of multiple paths. Changed to an array and now working as expected.

**Comment by stevendanna** [comment]
The matcher is now much more simple since logrotate_app has been converted to a custom resource.  I'm going to close this for now.
