### ISSUE TITLE
Release logrotate 2.0 to supermarket

### ISSUE THREAD

**Issue by sh9189** [stevendanna/logrotate#96]
@stevendanna Can we get logrotate 2.0 released to supermarket please?
cc @johnbellone

**Comment by stevendanna** [comment]
👍 I think this has been out there long enough.  We've only had one user mention the API change https://github.com/stevendanna/logrotate/issues/93 and they unfortunately never got back about their use case.

**Comment by stevendanna** [comment]
Done.
